/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tkobayas' at '12/14/18 5:53 PM' with Gradle 3.2.1
 *
 * @author tkobayas, @date 12/14/18 5:53 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
